# Generated by Django 5.1.1 on 2024-10-24 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('reg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ref_code', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
            ],
        ),
    ]
