# Generated by Django 5.1.1 on 2024-10-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Novaji', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mobile_number',
            new_name='mobile_network',
        ),
    ]
